hl7germany/basisprofil-de-r4

- extensions/Extension-gkv-besondere-personengruppe.xml
- extensions/Extension-icd-10-gm-diagnosesicherheit.xml
- terminologie/valuesets/ValueSet-kbv-s-icd-diagnosesicherheit.xml
- terminologie/valuesets/ValueSet-kbv-s-icd-seitenlokalisation.xml
"TJ" was Tibet and China, removed Tibet (sorry Tibet)
> fixed kbv uris

- ressourcen-profile/Profile-condition-de-icd10.xml
> Invariante ICD-8 hinzugefügt

- datentypen-profile/Profile-address-de-basis.xml
> Einschränkung von Address.line per DIN 5008

- terminologie/conceptmap/OPS-SNOMED-Category.ConceptMap.json
> ConceptMap OPS Klassentitel -> SNOMED-CT hinzugefügt

- ressourcen-profile/Profile-coverage-de-sel.xml
> Add PKV Identifier Slice to Coverage (Selbstzahler)

- extensions/Extension-gkv-abrechnendeIK.StructureDefinition.xml
- ressourcen-profile/Profile-coverage-de-gkv.xml
> Abrechnende IK als Extension modelliert, nicht als Slice

- extensions/Extension-dgkev-AufnahmegrundDritteStelle.StructureDefinition.xml
- extensions/Extension-dgkev-EntlassungsgrundErsteUndZweiteStelle.StructureDefinition.xml
- extensions/Extension-dkgev-AufnahmegrundErsteUndZweiteStelle.StructureDefinition.xml
- extensions/Extension-dkgev-AufnahmegrundVierteStelle.StructureDefinition.xml
- extensions/Extension-dkgev-Entlassungsgrund.StructureDefinition.xml
- extensions/Extension-dkgev-EntlassungsgrundDritteStelle.StructureDefinition.xml
> Extensions für P21 Elemente

- terminologie/valuesets/ValueSet-VitalSignDE-Atemfrequenz-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Blutdruck-Diastolisch-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Blutdruck-Systolisch-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Herzfrequenz-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Koerpergewicht-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Koerpertemperatur-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Kopfumfang-Snomed.json
- terminologie/valuesets/ValueSet-VitalSignDE-Sauerstoffsaettigung-Snomed.json
#7 ValueSets für SNOMED Slices
> snomed valuesets fuer vitalparameter hinzugefuegt

- extensions/Extension-Lebensphase.xml
- terminologie/valuesets/ValueSet-Lebensphase.xml
> Lebensphase Extension und ValueSet hinzugefügt

- terminologie/codesysteme/CodeSystem-dimdi-ops.xml
- terminologie/valuesets/ValueSet-ArgeIkKlassifikationVS.xml
- terminologie/valuesets/ValueSet-AufnahmeanlassVS.xml
- terminologie/valuesets/ValueSet-AufnahmeartVS.xml
- terminologie/valuesets/ValueSet-AufnahmegrundDritteStelleVS.xml
- terminologie/valuesets/ValueSet-AufnahmegrundErsteUndZweiteStelleVS.xml
- terminologie/valuesets/ValueSet-AufnahmegrundVierteStelleVS.xml
- terminologie/valuesets/ValueSet-EntlassungsgrundDritteStelleVS.xml
- terminologie/valuesets/ValueSet-EntlassungsgrundErsteUndZweiteStelleVS.xml
- terminologie/valuesets/ValueSet-FachabteilungsschluesselVS.xml
- terminologie/valuesets/ValueSet-dimdi-ops.xml
> added ops VS

- ressourcen-profile/Profile-observation-VitalSignDE.StructureDefinition.xml
> Observation.subject für Vitalparameter sollte nur auf Group oder Patient verweisen

- ressourcen-profile/Observation-pflegegrad.xml
- ressourcen-profile/Profile-observation-VitalSignDE_Atemfrequenz.StructureDefinition.xml
> Fix slicing over .code in Observation profiles

- terminologie/codesysteme/CodeSystem-identifier-type-de-basis.xml
> BSNR und LANR sind bereits in HL7 v2 Table 0203 enthalten

- ressourcen-profile/Profile-observation-VitalSignDE_Blutdruck.StructureDefinition.xml
> Add pattern for mm[Hg] to meanBp

- beispiele/Example-condition-ausrufezeichen-primaer.xml
- beispiele/Example-condition-ausrufezeichen-sekundaer.xml
- beispiele/Example-condition-kreuz-stern-primaer.xml
- beispiele/Example-condition-kreuz-stern-sekundaer.xml
- beispiele/Example-condition-minimal.xml
- beispiele/Example-condition-zustand-nach.xml
- beispiele/Example-observation-pflegegrad.xml
- datentypen-profile/Profile-coding-alpha-id-se.xml
- datentypen-profile/Profile-coding-alpha-id.xml
- datentypen-profile/Profile-coding-atc.xml
- datentypen-profile/Profile-coding-icd10gm.xml
- datentypen-profile/Profile-coding-ops.xml
- terminologie/codesysteme/CodeSystem-dimdi-alpha-id-se.xml
- terminologie/codesysteme/CodeSystem-dimdi-alpha-id.xml
- terminologie/codesysteme/CodeSystem-dimdi-atc.xml
- terminologie/codesysteme/CodeSystem-dimdi-icd-10-gm.xml
- terminologie/codesysteme/CodeSystem-dimdi-ops.xml
- terminologie/conceptmap/ConceptMap-OPS-SNOMED-Category.xml
- terminologie/valuesets/ValueSet-alpha-id.xml
- terminologie/valuesets/ValueSet-ask.xml
- terminologie/valuesets/ValueSet-atc.xml
- terminologie/valuesets/ValueSet-dimdi-icd10-gm.xml
- terminologie/valuesets/ValueSet-dimdi-ops.xml
- terminologie/valuesets/ValueSet-ops-pflegegrad.xml
Dimdi -> Bfarm in copyright und canonicals
> dimdi -> bfarm

- terminologie/codesysteme/CodeSystem-supplement-identifier-type-v2.xml
> Fix Supplement Identifier-Type

- datentypen-profile/Profile-identifier-kvid10.xml
- datentypen-profile/Profile-identifier-pseudo-kvid.xml
> Remove Identifier.use from kvid profiles

- datentypen-profile/Profile-identifier-pid.xml
> Remove Identifier.use from PID

- terminologie/codesysteme/CodeSystem-edqm-doseform.xml
> Fix canoncial for EDQM

- terminologie/codesysteme/CodeSystem-dkgev-abrechnungsart.xml
> Add PSY - Abrechungsart

- terminologie/codesysteme/CodeSystem-dkgev-Fachabteilungsschluessel.xml
> Fix Display Values für Fachabteilungsschlüssel

- datentypen-profile/Profile-address-de-basis.xml
> Fix fhirpath statement for value[x] selection

- ressourcen-profile/Profile-observation-grad-der-behinderung.json
- terminologie/codesysteme/CodeSystem-behinderung-merkzeichen-de.json
- terminologie/valuesets/ValueSet-behinderung-merkzeichen-de.json
Habe es nach bestem Wissen und Gewissen mit FSH erstellt. Ich freue mich über Rückmeldungen und Reviews
> #335 Grad der Behinderung: Profil, CS und VS hinzugefügt

- extensions/Extension-InformationRecipient-De.xml
> Add ExtensionInformationRecipient

- extensions/Extension-wahlleistungen.xml
- terminologie/codesysteme/CodeSystem-Wahlleistung-de.xml
- terminologie/valuesets/ValueSet-Wahlleistung-de.json
> Extension für Wahlleistungen hinzugefügt

- terminologie/codesysteme/CodeSystem-dkgev-abrechnungsart.xml
> Vorschlag SAP Erweiterung Abrechnungsart

- beispiele/Example-observation-grad-der-behinderung.json
- terminologie/codesysteme/CodeSystem-behinderung-merkzeichen-de.json
fehlendes Beispiel hinzugefügt
> Grad der behinderung

- terminologie/codesysteme/CodeSystem-behinderung-merkzeichen-de.json
oid für das CS für die Merkzeichen eingebaut
> oid eingebaut

- ressourcen-profile/Profile-coverage-de-gkv.xml
- ressourcen-profile/Profile-coverage-de-sel.xml
> Anpassung Slicing Coverage.type and Coverage.identifier

- datentypen-profile/Profile-identifier-bsnr.xml
> Füge bsnr-1 Constraint hinzu

- terminologie/namingsystems/NamingSystem-kzbv-zahnarztnummer.xml
> Fix Beschreibung namingSystem-KzbvZahnarztnummer

- extensions/Extension-AbrechnungsDiagnoseProzedur.json
- extensions/Extension-Abrechnungsart.json
- extensions/Extension-icd-10-gm-mehrfachcodierungs-kennzeichen.xml
- ressourcen-profile/Profile-observation-VitalSignDE_GCS.StructureDefinition.xml
- ressourcen-profile/Profile-observation-de-ekg.StructureDefinition.xml
- terminologie/codesysteme/CodeSystem-KontaktDiagnoseProzedur.json
- terminologie/codesysteme/CodeSystem-mehrfachkodierungs-kennzeichen.xml
- terminologie/valuesets/ValueSet-AbrechnungsDiagnoseProzedur.json
- terminologie/valuesets/ValueSet-DiagnoseTyp.json
- terminologie/valuesets/ValueSet-Diagnosesubtyp.json
- terminologie/valuesets/ValueSet-icd-mehrfachkodierungs-kennzeichen.xml
> Set status to active

- terminologie/codesysteme/CodeSystem-KontaktDiagnoseProzedur.json
- terminologie/valuesets/ValueSet-DiagnoseTyp.json
> Anpassungen Diagnose Typ

- datentypen-profile/Profile-coding-ask.xml
> Fix typo in ASK profile

- datentypen-profile/Profile-identifier-bsnr.xml
> Add bsnr-1

- terminologie/conceptmap/ConceptMap-OPS-SNOMED-Category.xml
> Fix targetCanonical in ConceptMap-OPS-SNOMED-Category

- ig/ImplementationGuide.json
- ig/markdown/Ressourcen-Observation-Skalen-und-Scores.md
Kapitel Skalen und Scores hinzugefügt, gemäß TC-Beschluss vom 13.10.2022 https://hl7germany.sharepoint.com/:w:/s/TCFHIR/ESAlLx9Ivn1FhNbU8ljY_j8BmHq3aFnw2RC5KAzHCAI9Og?e=VFj2U8
> Simone on fhir skalen und scores

- ig/markdown/Hinweise.md
- ig/markdown/Ressourcen-Observation-Skalen-und-Scores.md
Review beim nächsten TC-Meeting
> Simone on fhir standard levels

- ig/markdown/Ressourcen-Observation-Vitalparameter-Atemfrequenz.md
> Korrektur Link Atemfrequenz

- ig/markdown/ExtensionsfrAccount.md
> Fix extension url for ExtensionAbrechnungsDiagnoseProzedur in IG

- ig/markdown/LebenslangeZahnarztnummerZANR-Identifier.md
https://hl7germany.atlassian.net/browse/HFB-50
> HFB-50-Definition Zahnarztnummer inkonsistent

- resources/fsh-generated/resources/StructureDefinition-coverage-de-gkv.json
- resources/input/fsh/profiles/CoverageDeGkv.fsh
https://hl7germany.atlassian.net/browse/HFB-57
> HFB-57-coverage-de-gkv verweist textuell auf 30-stelligen Identifier

- ig/markdown/ExtensionsfrCondition.md
- resources/fsh-generated/resources/StructureDefinition-ExtensionLebensphase.json
- resources/input/fsh/extensions/ExtensionLebensphase.fsh
https://hl7germany.atlassian.net/browse/HFB-71
> Lebensphase-Extension dokumentiert und um Kontext Range erweitert

- resources/fsh-generated/resources/NamingSystem-namingSystem-goae.json
- resources/fsh-generated/resources/NamingSystem-namingSystem-gzae.json
- resources/input/fsh/profiles/NamingsystemDeBasis.fsh
https://hl7germany.atlassian.net/browse/HFB-62
> Definition von GOÄ/GZÄ NamingSystem hinzugefügt

- ig/markdown/Ressourcen-Condition-ICD-10-GM.md
https://hl7germany.atlassian.net/browse/HFB-61
> Füge Vorgaben zum Mapping von postkordinierten ICD-10-GM Codes auf Alpha-IDs hinzu

- ig/markdown/Home.md
https://hl7germany.atlassian.net/browse/HDB-300
> Added new author

- resources/fsh-generated/resources/NamingSystem-namingSystem-gkv-kvk-versichertennummer.json
- resources/fsh-generated/resources/NamingSystem-namingSystem-gkv-kvnr-30.json
- resources/fsh-generated/resources/NamingSystem-namingSystem-gkv-pseudo-kvid.json
- resources/input/fsh/profiles/NamingsystemDeBasis.fsh
> GKV -> KVZ10 in NamingSystem

- resources/fsh-generated/resources/StructureDefinition-identifier-kvid-10.json
- resources/input/fsh/invariants/kvid-2.fsh
> Verbesserte Formulierung: kvid-2

- resources/fsh-generated/resources/StructureDefinition-ExtensionAbrechnungsDiagnoseProzedur.json
- resources/input/fsh/extensions/ExtensionAbrechnungsDiagnoseProzedur.fsh
Fixes https://hl7germany.atlassian.net/browse/HFB-77
> Fix Kardinalitäten ExtensionAbrechnungsDiagnoseProzedur

- resources/fsh-generated/resources/StructureDefinition-ExtensionFachabteilungsschluessel301.json
- resources/input/fsh/extensions/ExtensionFachabteilungsschluessel301.fsh
Änderung als Technical Correction, die MS-Flags sollten entsprechend unserer Vorgaben nicht vorhanden sein
> Remove MS flags from ExtensionFachabteilungsschluessel301

- ig/markdown/Ressourcen-Patient-Addresse.md
- resources/fsh-generated/resources/Patient-Example-patient-address-de-basis.json
- resources/fsh-generated/resources/Patient-Example-patient-de-basis-address.json
- resources/fsh-generated/resources/StructureDefinition-address-de-basis.json
- resources/input/fsh/aliases.fsh
- resources/input/fsh/instances/Example-patient-address-de-basis.fsh
- resources/input/fsh/instances/Example-patient-de-basis-address.fsh
- resources/input/fsh/profiles/AddressDeBasis.fsh
Umsetzung der in #654 beschriebenen Änderungen:
- AddressDeBasis erweitert
- Beispiele und Dokumentation angepasst
Dieser PR ersetzt #655 (Quelle ist hier branch innerhalb des Repositories anstelle meines privaten Forks).
> Anpassung der Abbildung von Address.country
